# Generated by Django 4.0.1 on 2022-01-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_language_remove_book_language_book_langage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='Enter language for the book', max_length=20),
        ),
    ]
