# Generated by Django 4.0.1 on 2022-01-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_language_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='langage',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='Enter book language', max_length=20),
        ),
    ]
